## Spring view resolver set up
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

## H2 in-memory database
spring.datasource.url=jdbc:h2:mem:tododb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

## H2 console (http://localhost:8080/h2-console)
spring.h2.console.enabled=true

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Hibernate ddl auto
spring.jpa.hibernate.ddl-auto=create-drop
